name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: 'src\LocalizR\LocalizR.sln'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Register Github
      run : dotnet nuget add source --username vouzamo --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/vouzamo/index.json"
    - name: Version
      shell: pwsh
      run: ./scripts/versioning.ps1 $env:GITHUB_PATH $env:GITHUB_RUN_ID
    - name: Restore dependencies
      run: dotnet restore $SOLUTION
    - name: Build
      run: dotnet build $SOLUTION --no-restore
    - name: Test
      run: dotnet test $SOLUTION --no-build --verbosity normal
    - name: Pack
      run: dotnet pack $SOLUTION --configuration $BUILD_CONFIG
    - name: Publish
      if: github.ref == 'refs/heads/master'
      run: dotnet nuget push "**/LocalizR.Common.*.nupkg" --source "github" --skip-duplicate
